# version: '3.8'

services:
  backend:
    build:
      context: ./backend/CodeReviewAPI
      dockerfile: Dockerfile
    ports:
      - "5186:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend 

  db:
    image: postgres:16
    container_name: code_review_db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: codereviewdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes: 
  pgdata:
